if filereadable(expand(janus#pathjoin("~", ".gvimrc.before")))
  source janus#pathjoin("~", ".gvimrc.before")
endif

" CtrlP OS-X Menu remapping
if janus#is_plugin_enabled('ctrlp') && has("gui_macvim")
  macmenu &File.New\ Tab key=<D-S-t>
endif

if filereadable(expand(janus#pathjoin("~", ".gvimrc.after")))
  source janus#pathjoin("~", ".gvimrc.after")
endif
