""
"" Janus setup
""

" For Windows support we had to jump through some bootstrapping hoops. Sorry about that.
if has('win32')
    " Define paths. Now, you see, windows doesn't have proper symlinks that normal
    " users are allowed to create, so we copy the (g)vimrc instead of linking it.
    " Thus, the resolving does not work. Hard-coding paths is the result. It's kinda bad,
    " so please fix it if you can.
    let g:janus_path = escape(expand('~\.vim\janus'), ' ')
    let g:janus_vim_path = escape(expand(g:janus_path . '\vim'), ' ')
    let g:janus_custom_path = escape(expand('~\.janus'), ' ')
    " Source janus's core
    exe 'source ' . g:janus_vim_path . '\core\before\plugin\janus.vim'
else
    " Define paths
    let g:janus_path = escape(fnamemodify(resolve(expand("<sfile>:p")), ":h"), ' ')
    let g:janus_vim_path = escape(fnamemodify(resolve(expand("<sfile>:p" . "vim")), ":h"), ' ')
    let g:janus_custom_path = expand("~/.janus")
    " Source janus's core
    exe 'source ' . g:janus_vim_path . '/core/before/plugin/janus.vim'
endif

" You should note that groups will be processed by Pathogen in reverse
" order they were added.
call janus#add_group("tools")
call janus#add_group("langs")
call janus#add_group("colors")

""
"" Customisations
""

if filereadable(expand(janus#pathjoin("~", ".vimrc.before")))
  source janus#pathjoin("~", ".vimrc.before")
endif

" Disable plugins prior to loading pathogen
exe 'source ' . janus#pathjoin(g:janus_vim_path, 'core', 'plugins.vim')

""
"" Pathogen setup
""

" Load all groups, custom dir, and janus core
call janus#load_pathogen()

" .vimrc.after is loaded after the plugins have loaded
